library(data.table)
source('helpers/convert_strings.R')
source('data_manager/data_manager_functions.R')
source('model/diffeq.R')
source('model/age_mappings.R') 
NO.INTERVENTION = c()

load('cached/data.manager_global_2024-12-30.Rdata') # WITHOUT scaling calibration targets
source('model/parameter_mappings/age_mixing.R')
source('model/parameter_mappings/testing_projection.R')
source('model/parameter_mappings/age_sex_mixing_proportions.R')
source('model/parameter_mappings/age_sex_transmission_multipliers.R')
source('model/parameter_mappings/engagement_disengagement_data.R')
source('model/parameters.R')
source('model/get_initial_population.R')
source('model/simplot.R')
source('calibration/likelihood/likelihood.R')
#source("calibration/likelihood/individual_likelihoods.R")
source('calibration/make_joint_distribution.R')
source('calibration/prior_distributions/kenya_prior.R')
source('calibration/prior_distributions/south_africa_prior.R')
source('calibration/prior_distributions/france_prior.R')
source('calibration/prior_distributions/var_blocks.R')
source('calibration/set_likelihood_and_prior.R')
source('future_projections/create_and_run_interventions_functions.R')
source('future_projections/extract_projection_results.R')